version: "2"

services:
  techtalk-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.0
    container_name: techtalk-elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 8200:9200
      - 8300:9300
    environment:
      ES_JAVA_OPTS: -Xmx256m -Xms256m
    networks:
      - elk
    mem_limit: 1g

  techtalk-logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.0
    container_name: techtalk-logstash
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - 4000:5000
    environment:
      LS_JAVA_OPTS: -Xmx256m -Xms256m
    networks:
      - elk
    depends_on:
      - techtalk-elasticsearch
    mem_limit: 1g

  techtalk-kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.4
    container_name: techtalk-kibana
    ports:
      - 4601:5601
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    networks:
      - elk
    depends_on:
      - techtalk-elasticsearch
    mem_limit: 1g

networks:
  elk:
    driver: bridge